# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TestGoreleaser < Formula
  desc "Testing gorelaser."
  homepage "https://??.io/"
  version "0.0.10"

  on_macos do
    on_intel do
      url "https://github.com/gtrrz-victor/test-goreleaser/releases/download/v0.0.10/test-goreleaser-0.0.10-darwin-amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "c04aa6b8ab3eee1a530a847a57fcc10a40567045fc41386cc9cf5b61a3a61eae"

      def install
        bin.install "gttest"
      end
    end
    on_arm do
      url "https://github.com/gtrrz-victor/test-goreleaser/releases/download/v0.0.10/test-goreleaser-0.0.10-darwin-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "1b50cf4e5a67607fc499e05ed77adf409e0eb2bdd2c1c097d62f3c7004fecf66"

      def install
        bin.install "gttest"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gtrrz-victor/test-goreleaser/releases/download/v0.0.10/test-goreleaser-0.0.10-linux-amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "8b937b0944150e6e5fd8cb1cd38d8de421f20d4310619a59b11f0b3c09004e3e"

        def install
          bin.install "gttest"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gtrrz-victor/test-goreleaser/releases/download/v0.0.10/test-goreleaser-0.0.10-linux-arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "d9c69dc56c223086b8f1fdaff32409c806b3805b0acef3508351adfe07abc629"

        def install
          bin.install "gttest"
        end
      end
    end
  end

  test do
    system "#{bin}"
  end
end
