# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TestGoreleaser < Formula
  desc "Testing gorelaser."
  homepage "https://??.io/"
  version "0.3.0"

  on_macos do
    on_intel do
      url "https://github.com/gtrrz-victor/test-goreleaser/releases/download/0.3.0/test-goreleaser-0.3.0-darwin-amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "b553278fdee4badb8735903d01d77f7002a75b103caac9f288e4b6a268de344b"

      def install
        bin.install "gttest"
      end
    end
    on_arm do
      url "https://github.com/gtrrz-victor/test-goreleaser/releases/download/0.3.0/test-goreleaser-0.3.0-darwin-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "24edccbe34b1d1ec5dee48d5b7239232ebd2e8c572e1c149a5f8cf5700883733"

      def install
        bin.install "gttest"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gtrrz-victor/test-goreleaser/releases/download/0.3.0/test-goreleaser-0.3.0-linux-amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "c81ce9fa5127d00f226107c7d8f3bebbf304a54010ee46516ed0b18f9b5cac43"

        def install
          bin.install "gttest"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gtrrz-victor/test-goreleaser/releases/download/0.3.0/test-goreleaser-0.3.0-linux-arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "ac7aad58d2727e2f2b83f90dc3886fb3e13260bae4b3c92af3f07121fa373143"

        def install
          bin.install "gttest"
        end
      end
    end
  end

  test do
    system "#{bin}"
  end
end
